[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = { version = "4.9.0", features = ["rustls-0_23"] }
env_logger = "0.11.5"
log = "0.4.22"
common = { path = "../common/" }
