# https://stackoverflow.com/a/75246287
# docker-compose up -d
# docker-compose logs gatewaydb
# docker-compose down -v # remove volumes
# psql -h localhost -p 3002 -U postgres -d gatewaydb
# psql -h localhost -p 3004 -U postgres -d infosdb
version: '3.9'

services:

  gatewaydb:
    container_name: gatewaydb
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gatewaydb
      PGDATA: /data/postgres
    volumes:
      - gatewaydb:/data/postgres
    ports:
      - "3002:5432"
    networks:
      - gatewaydb
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  infosdb:
    container_name: infosdb
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: infosdb
      PGDATA: /data/postgres
    volumes:
      - infosdb:/data/postgres
    ports:
      - "3004:5432"
    networks:
      - gatewaydb
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

networks:
  gatewaydb:
    driver: bridge
  infosdb:
    driver: bridge

volumes:
  gatewaydb:
  infosdb:
