[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = { version = "4.9.0", features = ["rustls-0_23"] }
serde = { version = "1.0.210", features = ["serde_derive"] }
common = { path = "../common/"}
env_logger = "0.11.5"
log = "0.4.22"
