/*
 Generated by typeshare 1.11.0
*/


/**
 * this merges data from "gateway" (which is not really a gateway at this point)
 * and inventory services, represent data to be send to the client, from the repo run
 * ```sh
 * typeshare common --lang=typescript --output-folder=common
 * ```
 * https://github.com/1Password/typeshare/blob/main/docs/src/usage/annotations.md#serialize-as-another-type
 */
export interface Order {
	id: string;
	user_id: string;
	product_id: string;
	available_quantity: number;
}

